### ISSUE TITLE
object mapper deserializing case class with default values inconsistently

### ISSUE THREAD

**Issue by Nimrod007** [FasterXML/jackson-module-scala#159]
Getting flaky results running this test.
object mapper deserializing inconsistently. 
Person object with missing param name is sometimes null and sometimes empty string.
expecting always to get empty string.
please run the test multiple times to check the flaky results.

```
      import com.fasterxml.jackson.databind.ObjectMapper
      import com.fasterxml.jackson.module.scala.DefaultScalaModule
      import org.specs2.mutable.SpecificationWithJUnit

      case class Person(id:Int,name:String=""){
        def this() = this(1,"")
      }

      case class PersonWithNoName(id:Int)

      class MapperTest extends SpecificationWithJUnit {

        "mapper" should {

          "not have person with null in name" in {

            val mapper = new ObjectMapper()
            mapper.registerModule(DefaultScalaModule)

            val personWithNoNameJsonString = mapper.writeValueAsString(PersonWithNoName(id = 1))

            val person = mapper.readValue(personWithNoNameJsonString,classOf[Person])

            person.name must not(beNull[String]).setMessage("Name should not be null")
          }

        }

      }
```

After running multiple times some results are valid and some are :
"
Name should not be null
java.lang.Exception: Name should not be null
"

**Comment by kylejmcintyre** [comment]
The inconsistency is due to the fact that the list of constructors coughed up in BeanIntrospector.findConstructorParam() is non-deterministic for a given JVM process instantiation, at least for some JVM implementations. So the call to headOption might return the no-arg constructor or it might return the primary constructor. Worked around this by adding the @JsonCreator annotation to my def this() constructor, which I believe causes Jackson to later trump what the jackson scala module is providing.

**Comment by CHENXCHEN** [comment]
Meet same problem, add @JsonCreator annotation to def this() constructor to solve the issue.

**Comment by pjfanning** [comment]
In jackson-module-scala 2.12.x, this seems to work - see tests like https://github.com/FasterXML/jackson-module-scala/commit/85550eaf009b80af0714417389316c5f765b550d - constructors are ordered by number of params (descending) to get deterministic behaviour
