### ISSUE TITLE
version=${version} in 2.5.0-SNAPSHOT build.properties

### ISSUE THREAD

**Issue by clamothe** [FasterXML/jackson-module-scala#180]
Using 2.5.0-SNAPSHOT with Jackson 2.5.0, registering the module results in an exception thrown from line 67 of JacksonModule.scala.
`com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.5.0`

I noticed that `buildProps("version") == "${version}"` and that build.properties in the current snapshot jar contains `version=${version}`.

Building the project locally with `sbt package` creates a JAR containing a proper build.properties with `version=2.5.0-SNAPSHOT`. I'm not sure why the JAR deployed to the oss snapshot repository differs from that which I built locally.

Thanks!

**Comment by clamothe** [comment]
This is using scala 2.11.4

**Comment by clamothe** [comment]
I noticed that while the jar produced by `sbt package` has the correct version, that produced by `sbt publishM2` contains the placeholder.

**Comment by christophercurrie** [comment]
Thanks for catching this! I'll look into what's wrong with my xsbt-filter configuration.

**Comment by clamothe** [comment]
Great, thanks

**Comment by christophercurrie** [comment]
It turns out to have been an incompatibility between [xsbt-filter](https://github.com/sdb/xsbt-filter) and [sbt-osgi](https://github.com/sbt/sbt-osgi). I've dropped the use of xsbt-filter and replaced it with a custom resource generator. I've pushed new snapshots for 2.4.5 and 2.5.0, and verified that the deployed jars contain the correct property files.

Fixed by 13b1a4b.
