### ISSUE TITLE
Deserialization of a HashMap wrapped into an Option

### ISSUE THREAD

**Issue by david-bouyssie** [FasterXML/jackson-module-scala#184]
I have a simple case class with this kind of defintion:

````
case class Dummy(
  @JsonDeserialize( contentAs = classOf[scala.collection.immutable.HashMap[Long,Long]])
  countByDay: Option[scala.collection.immutable.HashMap[Long,Long]] = None
)
````

When I try to access the keys of countByDay the following exception is thrown:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long

Am I wrong with the @JsonDeserialize annotation or this a current limitation of the scala module ?

**Comment by nbauernfeind** [comment]
I think this comment is going to be useful to you:
https://github.com/FasterXML/jackson-module-scala/issues/175#issuecomment-69513744

You probably want to try java.lang.Long instead of Long.

**Comment by nbauernfeind** [comment]
Or perhaps it would be better to send you straight to the FAQ: https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges

**Comment by david-bouyssie** [comment]
Switched to

```
case class Dummy(
    @JsonDeserialize( contentAs = classOf[scala.collection.immutable.HashMap[java.lang.Long,java.lang.Long]])
    countByDay: Option[scala.collection.immutable.HashMap[Long,Long]] = None
  )
```

but still the same error

**Comment by nbauernfeind** [comment]
Ok, then it must be related to classOf not keeping around type parameter information. I thought maybe, potentially, it was going to work differently for compile-time annotations. Sorry for sending you down rabbit holes. I should've tried a few examples first.

This works:
```scala
case class Dummy(countByDay: Option[immutable.HashMap[java.lang.Long, java.lang.Long]] = None)

object Test extends App {
  val om = new ObjectMapper with ScalaObjectMapper
  om.registerModule(DefaultScalaModule)

  println(om.readValue[Dummy]("{}"))
  println(om.readValue[Dummy]("{\"countByDay\": { \"5\": 25 } }"))
}
```

Yields output:
```
Dummy(None)
Dummy(Some(Map(5 -> 25)))
```

Actually, any variation seems to be working for me. What is your test-case? What version of jackson are you using?

**Comment by david-bouyssie** [comment]
Ok. Your example works (under jackson 2.3.1). I think the reason why it fails in my code is that I'm wrapping the ObjectMapper into a custom class defining a deserialize method:

```
    def deserialize[T:Manifest](value: String ) : T  = {
      objectMapper.readValue(value, typeReference[T])
    }
````

Using the manifest may lead to type information loss ?

**Comment by david-bouyssie** [comment]
And here is how typeReference is computed:
````
private [this] def typeReference[T: Manifest] = new TypeReference[T] {
      override def getType = typeFromManifest(manifest[T])
    }
    
    private [this] def typeFromManifest(m: Manifest[_]): Type = {
      val runtimeClass = m.runtimeClass 
      if (m.typeArguments.isEmpty || runtimeClass.isArray() ) { runtimeClass } // was m.erasure in Scala 2.9
      else new ParameterizedType {
        def getRawType = runtimeClass  // was m.erasure in Scala 2.9
        def getActualTypeArguments = m.typeArguments.map(typeFromManifest).toArray
        def getOwnerType = null
      }
    }
```

**Comment by nbauernfeind** [comment]
Hey! That code looks very familiar =).

Using a Manifest is absolutely the right way to go. The manifest actually retains type information. The `readValue` method I referenced also uses a Manifest to generate a TypeReference. I'm not actually sure what is wrong with the code snippet that you pasted; that is exactly the same snippet that ScalaObjectMapper originally used. However, it was changed (I don't really understand why); It now computes a JavaType.

See: https://github.com/FasterXML/jackson-module-scala/blob/master/src/main/scala/com/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper.scala#L56

Consider trying:
```scala
objectMapper.readValue(value, new ObjectMapper with ScalaObjectMapper().constructType[T])
```

Obviously, it's not efficient. However, it will tell you if the issue is the layer that converts Manifest to something useful for Jackson.

**Comment by david-bouyssie** [comment]
Thank you for the constructType type. I have an objectMapper reference in my wrapper so I will translate your code into: 
```scala
objectMapper.readValue(value, objectMapper.constructType[T] )
```
This way I assume I won't have performance penalty, isn't it ?

About my issue, I understood why your example works. The println() use the toString method of the HashMap and thus it doesn't unbox the keys into Long.

Try the following line:
```scala
om.readValue[Dummy]("{\"countByDay\": { \"5\": 25 } }").countByDay.get.keys.head.asInstanceOf[java.lang.Long]
```

**Comment by christophercurrie** [comment]
Sorry, I didn't look at this thread closely until just now. I don't believe what you're trying to do is possible in the current version of the module.

```scala
@JsonDeserialize(contentAs=classOf[immutable.HashMap[Long,Long]])
```

Is the same as

```scala
@JsonDeserialize(contentAs=classOf[immutable.HashMap[_,_]])
```

because the annotation's value must be a *compile-type constant*, and JVM compile time class values are aways raw classes without type parameter information. There's no language construct in Scala that can remove this limitation. When Jackson doesn't have type information for a JSON number, it uses the *smallest* type of [Integer, Long, Float, Double] into which the number can fit.

Your best workaround in this case is to not use `Option` when deserializing collections. This does open up the possibility of null values; there's an open feature request (FasterXML/jackson-databind#347) to provide a configuration setting to de-serialize `null` or missing properties into an empty collection, but that's not available right now.

A feature I can (and should) implement for Scala is #122, which would allow you to work around this problem by using subclasses of collections, as in:

```
class MapLongToLong extends immutable.HashMap[java.lang.Long,java.lang.Long]
```

which could be paired with `contentAs` to enable capturing the type information in a concrete class. You'd still have to use Java `Long` instead of Scala `Long` for the reasons in the FAQ.

**Comment by david-bouyssie** [comment]
Ok thanks for these clear explanations. Maybe you should add your post to the FAQ.

I changed my model to something like:
```scala
case class Dummy(
  @JsonDeserialize( keyAs = classOf[java.lang.Long], contentAs = classOf[java.lang.Long] )
  private val countByDay: scala.collection.immutable.HashMap[java.lang.Long,java.lang.Long] = null
) {
  def getCountByDay() = Option(countByDay)
}
```

However I still have the "java.lang.String cannot be cast to java.lang.Long" exception.
Where am I wrong ?
Note that I'm using the version 2.3.1 (jackson + Scala module).

**Comment by christophercurrie** [comment]
In this case, because you're using the Java `Long`, you shouldn't need to specify "keyAs" or "contentAs" at all. Jackson can find the type parameters using reflection, since the map is a member variable. If you remove the @JsonDeserialize annotation, it should start to work; the annotation is now overriding the default behavior that allows it to convert string keys to longs.

**Comment by cowtowncoder** [comment]
Also: version 2.3.1 is rather old. I think you really need to check with either 2.5.0 (ideal), or 2.4.4.
Or at very least latest 2.3.x, which I thnik is 2.3.5.

**Comment by david-bouyssie** [comment]
Upgrading to 2.3.5 or above seems to solve this issue, which can now be closed. Sorry about that.
I had some issues to upgrade jackson because I was using my own method to build the TypeReference (see above). As suggested by nbauernfeind I'm now using
the ScalaObjectMapper.constructType method in my wrapper. This seems to fix the issues I had. I'm still testing if I don't have indesirable effects (relative to this upgrade) in projects depending on my library, but this should not be related to this issue.

Here is my final version of my Dummy case class for people who would be interested to do the same thing:
```scala
case class Dummy(
  @JsonDeserialize( keyAs = classOf[java.lang.Long], contentAs = classOf[java.lang.Long] )
  private val countByDay: scala.collection.immutable.HashMap[Long,Long] = null
) {
  def getCountByDay() = Option(countByDay)
}
```
