### ISSUE TITLE
serializating enumerations leads to an extra property in json

### ISSUE THREAD

**Issue by asharma-apixio** [FasterXML/jackson-module-scala#215]
Following the solution prescribed here

The enum declaration is as 
    object UserStatus extends Enumeration {
      type UserStatus = Value
      val Active, Paused = Value
    }
    class UserStatusType extends TypeReference[UserStatus.type]
    case class UserStatusHolder(@JsonScalaEnumeration(classOf[UserStatusType]) enum:   UserStatus.UserStatus)

The dto is declared as

    class UserInfo(val emailAddress: String, val  userStatus:UserStatusHolder) {
    
    }

the serialization code is

    val mapper = new ObjectMapper()
      mapper.registerModule(DefaultScalaModule)
    
         def serialize(value: Any): String = {
            import java.io.StringWriter
            val writer = new StringWriter()
            mapper.writeValue(writer, value)
            writer.toString
          }

The resulting json serialization is 

    {
    	"emailAddress":"user1@test.com",
    	"userStatus":{"enum":"Active"}
    }

Is it possible to get it the following form ? 

    {
    	"emailAddress":"user1@test.com",
    	"userStatus":"Active"
    }

  [1]: https://github.com/FasterXML/jackson-module-scala/wiki/Enumerations

**Comment by christophercurrie** [comment]
The wiki has [an article on this subject](https://github.com/FasterXML/jackson-module-scala/wiki/Enumerations).

**Comment by wuservices** [comment]
@christophercurrie the article was very informative. It seemed like the main difficulty was around getting an instance to use `withName` to instantiate a value during deserialization.

If so, could there be a way to use the `AnnotatedEnumerationSerializer` logic (or just `value.toString`) if we don't care about deserializing?

For example, I ran into this when using [logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator), for structured JSON logging.

You may often want to log something like this where you'd never need to deserialize, and don't want an object with `enumClass` and `value` in your logs:
```
logger.info("log day of week {}", keyValue("weekday", Weekday.Mon))
```

In this scenario, it'd be undesirable to create an extra holder object where you could add an annotation due to the extra boilerplate and because you don't want to nest `weekday` inside another object in the logs. You can of course just use `Weekday.Mon.toString` directly, but this becomes hard for all to remember, and tedious and unreadable to transform when lots of `Enumeration` objects are used in a deeply nested structure.

Is there a more convenient way to serialize without the annotation, or just to always use `.toString` for `Enumeration` serialization?

**Comment by cowtowncoder** [comment]
@wuservices For usage questions, chat may be better venue:

https://gitter.im/FasterXML/jackson-databind

or mailing list 

https://groups.google.com/forum/#!forum/jackson-user
