### ISSUE TITLE
map with 'Int' keys restored back with 'String' keys

### ISSUE THREAD

**Issue by kgignatyev** [FasterXML/jackson-module-scala#219]
lets say we have 
val map = new mutable.HashMap[Int, String]()
it gets serialized to
{"2":"a","1":"a"}
and after deserialization the map contains 'String keys' so 

val restoredMap =  mapper.readValue(serializedMap, classOf[mutable.HashMap[Int, String]])
    restoredMap.keys.foreach(k=> k.getClass)

causes exeption
 java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
  at kgi.mcytravel.wsite.MapSerializationTest$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(MapSerializationTest.scala:45)
  at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
  at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
  at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
  at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
  at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
  

======== test code below ==========
package kgi.mcytravel.wsite

import com.fasterxml.jackson.core.`type`.TypeReference
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
import org.scalatest.FunSuite

import scala.collection.mutable

class MapSerializationTest extends FunSuite{

  val map = new mutable.HashMap[Int, String]()
  map.put(1,"a")
  map.put(2,"a")

  val mapper: ObjectMapper = {
    val res = new ObjectMapper  with ScalaObjectMapper
    res.registerModule(DefaultScalaModule)
    res
  }

  val serializedMap = mapper.writeValueAsString( map )

  println(serializedMap)

  test("map serialization test via TypeRef"){
    val restoredMap =  mapper.readValue(serializedMap, new TypeReference[mutable.HashMap[Int, String]]{}).asInstanceOf[mutable.HashMap[Int, String]]
    restoredMap.keys.foreach(k=> k.getClass)
    assert(true)
  }

  test("map serialization test"){

    val restoredMap =  mapper.readValue(serializedMap, classOf[mutable.HashMap[Int, String]])
    restoredMap.keys.foreach(k=> k.getClass)
    assert(true)
  }

}

**Comment by kgignatyev** [comment]
looks like #131 came back to life

**Comment by christophercurrie** [comment]
This is not related to #131, it is related to value type handling as mentioned [in the FAQ](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges):

> all primitive type parameters are represented as `Object` to the JVM.

That said, your specific test case would fail even without this issue, because `classOf` removes any type parameters that might be available:

```scala
mapper.readValue(serializedMap, classOf[mutable.HashMap[Int, String]]) // effectively HashMap[_,_]
```

In order to ensure the type parameters get sent, you need to use type references:

```scala
import com.fasterxml.jackson.core.`type`.TypeReference
mapper.readValue(serializedMap, new TypeReference[mutable.HashMap[Int, String]]{})
```

This construction preserves the type parameters as the JVM sees them. It still doesn't work, sadly, because the JVM type parameter is Object. For your test case, you'd need to specify `java.lang.Integer`:

```scala
import com.fasterxml.jackson.core.`type`.TypeReference
mapper.readValue(serializedMap, new TypeReference[mutable.HashMap[java.lang.Integer, String]]{})
```

For cases where you cannot change the key's type, the workaround is to wrap the Map in an object, and annotate the map property with `@JsonDeserialize(keyAs=classOf[java.lang.Integer])`, to provide the type information that the JVM doesn't have.

```scala
class MapWrapper(
  @JsonDeserialze(keyAs = classOf[java.lang.Integer])
  val m: mutable.HashMap[Int,String]
)
```

**Comment by kgignatyev** [comment]
That works, thank you! My fault, forgot that Int is Int is descendant of AnyVal...
