### ISSUE TITLE
Afterburner Interferes With Options Respecting Include.NON_NULL

### ISSUE THREAD

**Issue by omervk** [FasterXML/jackson-module-scala#226]
If Afterburner ([`jackson-module-afterburner`](https://github.com/FasterXML/jackson-module-afterburner)) is registered on an ObjectMapper before `DefaultScalaModule`, it interferes with (at least) how `None` is serialized when `Include.NON_NULL` is in play.

```scala
case class A(foo: Option[String] = None)
class B {
    @JsonProperty val foo: Option[String] = None
}

val objectMapper = new ObjectMapper()
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL)
objectMapper.registerModule(new AfterburnerModule)
objectMapper.registerModule(DefaultScalaModule)

val caseClassJson = objectMapper.writeValueAsString(A())
val objectJson = objectMapper.writeValueAsString(new B())
val anonymousObjectJson = objectMapper.writeValueAsString(new {
    @JsonProperty val foo: Option[String] = None
})
```

Expected:
```
caseClassJson == "{}"
objectJson == "{}"
anonymousObjectJson == "{}"
```

Actual:
```
caseClassJson == """{ "foo": null }"""
objectJson == """{ "foo": null }"""
anonymousObjectJson == "{}"
```

**Comment by christophercurrie** [comment]
Interesting. Does the order of registering the modules make a difference?

**Comment by cowtowncoder** [comment]
Another thing that may be of importance here is that Jackson 2.6 has improved support for "referential" types, aimed at better support for `Option`/`Optional`s (and some other similar types like `AtomicReference`).
There are things module needs to do to take advantage of this, we may need to verify that Scala module does those. This matters mostly because `jackson-databind` is responsible for much/most of actual serialization exclusion handling.

@christophercurrie JDK8 module and Guava have relevant code, and maybe former is simpler example, on how to resolve option(al) type as `ReferenceType`, if that is not yet done (I forget whether we talked about this earlier)

**Comment by christophercurrie** [comment]
I don't think that the Scala module has yet picked up on that. I'll dig into the JDK8 module's  examples as time allows.

**Comment by omervk** [comment]
@christophercurrie

> Interesting. Does the order of registering the modules make a difference?

Yes, registering Afterburner after the Scala module does not cause this issue. I am not sure whether it might cause issues with Afterburner, though.

**Comment by omervk** [comment]
As a side-effect of the 2.7.4 release, the non-standard `NON_NULL` behavior with respect to `Option` has been fixed and the correct `NON_ABSENT` should be used instead. Original issue has also been resolved.

Thanks 👍

**Comment by cowtowncoder** [comment]
@omervk Thank you for verifying this.
