### ISSUE TITLE
None is written as null with Include.NON_NULL set since 2.7.4 (also another issue with 2.7.3 and earlier)

### ISSUE THREAD

**Issue by dimatkach** [FasterXML/jackson-module-scala#325]
`case class Foo(bar: Options[String] = None)` 
gets written as `{ "bar": null }`.
This used to work for me before (at least, in 2.6.6). Not sure at which point it got broken, I ran into this issue trying to upgrade to `2.8.8`.

*Update*: Looks like the last version it works right is `2.7.3`. I haven't checked everything after that, but `2.7.{4,5,9}` and `2.8.0` are all broken. 

Unfortunately, I cannot use `2.7.3` or `2.7.2`, because they have another issue (seems to be gone in 2.8.8, so I am not reporting it separately): if I have a `trait` extending a `Product`, and a case class with a field, that's `Option` of that trait, then serializing that case class always writes that field as empty:
       
       trait Prod extends Produc1[String] { def x: String; def canEqual(o: Any) = ???; def _1 = x }
       class Foo(val x: String) extends Prod
       case class Bar(bar: Prod)
       case class Bat(bam: Option[Foo])
       case class Baz(baz: Option[Prod])

       mapper.writeValueAsString(new Foo("bar")) // { "x" = "bar" } - good
       mapper.writeValueAsString(Bar(new Foo("bar"))) // { "bar" = { "x" = "bar" }} - good
       mapper.writeValueAsString(Bat(Some(new Foo("bar")))) // { "bat" = { "x" = "bar" }} - good
       mapper.writeValueAsString(Baz(Some(new Foo("bar")))) // { "baz" = {}} - ????

So, it looks like I am stuck with 2.6.6. for now ... :(

**Comment by cowtowncoder** [comment]
@dimatkach What you want to do here is to use value `NON_ABSENT` instead of `NON_NULL`, to omit absent value from being serialized. You can read Javadocs for `@JsonInclude`:

http://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonInclude.html

to see full definitions of intended operation of values.

Now: I think handling is correct: `NON_NULL` explicitly only refers to Java (or any JVM Language, Scala include) `null`s but NOT to possible json serialization as null. While distinction may seem unimportant it is unfortunately quite distinct from serialization side: databinding can not control transformation from JVM value (non-null here) into external json value. Other values (`NON_ABSENT`, `NON_EMPTY`) do perform additional checks, so that serializer is called to see if a non-null value falls within category of values to exclude -- such as absent referential values, or empty collections. Also note that values are super-/subsets of each other: `NON_EMPTY` also excludes everything that `NON_ABSENT` does, and `NON_ABSENT` includes `NON_NULL`.

Exact implementation did indeed change a bit up until version 2.7 (and, regrettably, it seems, for one of patch versions, at least for Scala module?). Behavior should be stable from this point on.

I hope this helps.
