### ISSUE TITLE
Serialize Long keys in Map as Strings

### ISSUE THREAD

**Issue by angelcervera** [FasterXML/jackson-module-scala#347]
I try to serialize an object with an inner Map using a Long as key, but the serializer transforms the Long into a String.

Is it a BUG? Am I doing something wrong?

```scala
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

case class InnerMap(map: Map[Long, Long])

object CrazyJackson {

  def main(args: Array[String]): Unit = {
    val mapper = new ObjectMapper() with ScalaObjectMapper
    mapper.registerModule(DefaultScalaModule)

    val innerMap = InnerMap(Map(1L->1L))
    val serialized = mapper.writeValueAsString(innerMap)
    val newObj = mapper.readValue(serialized, classOf[InnerMap])
    println(serialized) // Why the key is serialized as a String?
    println(innerMap)
    println(newObj)
    assert(newObj == innerMap)
  }

}
```
The **assert fails** and the output of the println(serialized) statement is :

`{"map":{"1":1}}`
It is strange that printing newObj and innerMap is the same:

```
InnerMap(Map(1 -> 1))
InnerMap(Map(1 -> 1))
```
I must use this version because of Spark dependencies:

- Scala 2.11.11
- jackson-module-scala 2.6.5 and also test with version 2.9.1 with same result.

Example: https://github.com/angelcervera/jackson-scala-map-bug
Ask in [Stackoverflow](https://stackoverflow.com/questions/46588897/jackson-module-scala-serialize-long-keys-in-map-as-strings)

**Comment by angelcervera** [comment]
As Varren responded,
JSON allows key names to be strings only. ECMA-404 The JSON Data Interchange Standard
An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs. A name is a string.

**Comment by cowtowncoder** [comment]
Correct. Some other dataformats allow non-String keys, and there are some efforts to retain key type there (for Protobuf, CBOR f.ex). But with JSON String keys need to be used.

Jackson does still attempt to retrieve declared Java/Scala-side type on deserialization, when type information is available.

**Comment by angelcervera** [comment]
Hi @cowtowncoder 
You said

> Jackson does still attempt to retrieve declared Java/Scala-side type on deserialization, when type information is available.

But I think that that it is not true 100%.
As you can see in the example, the definition is `case class InnerMap(map: Map[Long, Long])` but Jackson is not extracting the type of the Key from the type definition `Map[Long, Long])`

I think that in this case, the information is available in the type declaration. Why is necessary an annotation?

I updated the title and the example, adding the same test using Circle. In this case, it is working as I expected.

To be honest, I don't know if open the issue again.

**Comment by cowtowncoder** [comment]
@angelcervera I don't do Scala (I did not write this module nor maintain it), so unfortunately all I can say is that if at JVM level `Map` declaration has key type available, deserialization does use that. Annotation should not be needed unless type declaration is too vague (like `Map<Object,Object>`).

I hope one of Scala module developers ( @christophercurrie @mbknor @nbauernfeind ) might be able to help with Scala aspects. I can help if there is Java-only reproduction of the issue, although I am not aware of any problems in this area.

**Comment by umcodemonkey** [comment]
This is another form of the FAQ item [Deserializing `Option[Int]` and other primitive challenges](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges). In short, Scala does *not* provide JVM level type information for intrinsic types used as generic parameters, and so the JVM signature for the type is exactly `Map<Object,Object>`, which makes it useless to Jackson for making any type-informed decisions.

The long term solution to this problem is to use Scala reflection to provide better type information to Jackson than is provided by the JVM. Scala reflection has gaps that make this solution imperfect, but better than what is done today.

The short term solution is, as called out in the FAQ, to use the `@JsonDeserialize` annotation with the properties `keyAs` and `contentAs` set to specify the types for the map keys and values, respectively.

**Comment by christophercurrie** [comment]
This is another form of the FAQ item [Deserializing `Option[Int]` and other primitive challenges](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges). In short, Scala does *not* provide JVM level type information for intrinsic types used as generic parameters, and so the JVM signature for the type is exactly `Map<Object,Object>`, which makes it useless to Jackson for making any type-informed decisions.

The long term solution to this problem is to use Scala reflection to provide better type information to Jackson than is provided by the JVM. Scala reflection has gaps that make this solution imperfect, but better than what is done today.

The short term solution is, as called out in the FAQ, to use the `@JsonDeserialize` annotation with the properties `keyAs` and `contentAs` set to specify the types for the map keys and values, respectively.

**Comment by angelcervera** [comment]
Thx @christophercurrie 
In my case, I don't like to annotate because the model is shared between different projects, so it is in a different project/module. I don't want to create a model that is tied to a Json library. So I prefer the solution of Circe.

Anyway, good to know these limitations about Scala reflection and why this small issue.

Again, thanks.
