### ISSUE TITLE
Change in behavior between Jackson 2.6 and 2.9

### ISSUE THREAD

**Issue by raiju** [FasterXML/jackson-module-scala#387]
Between 2.6.7 & 2.9.6 there was a change of behavior in how `@JsonIgnore` is handled.

This case class round-trips in 2.6 but not in 2.9:
```
case class Sample(foo: String) {
  @JsonIgnore
  def getFoo: String = foo
}
```

This case class round trips in both 2.6 and 2.9:
```
case class Sample(@(JsonProperty @field) foo: String) {
  @JsonIgnore
  def getFoo: String = foo
}
```

I can see arguments for both solutions (taking into account the principals laid out in https://github.com/FasterXML/jackson-databind/blob/master/README.md#annotations-ignoring-properties):
 - For 2.6: a `case class` should implicitly define `@JsonProperty` for each field (including in the constructor) due to the case class semantics; the `@JsonIgnore` only applies to the `getFoo` method (the fact that it gets auto-discovered to being the getter of `foo` being immaterial)
 - For 2.9: the `@JsonIgnore` annotation should take precedence over default annotations (as in, an annotation on a getter should affect all getters/setters of that property).

I can't find any documentation for this change, nor where it was introduced. Was this change intended? Do we expect the new behavior to remain? (Happy to PR in a test case to enforce that)

**Comment by cowtowncoder** [comment]
I don't work on this module, but I think that given that 2.9 is used much much more than 2.6, and new behavior in effect for quite a while, 2.9 behavior is the one to retain.
I don't know origin if change, or whether it was intentional.

However, with quick glance, to me 2.9 does look closer to intended behavior, if I understand what is happening -- a single `@JsonIgnore` annotation for any accessor indicating property `foo` would fully remove such property. If specific accessors (field, getter/setter, constructor argument) is to be blocked, then "split" approach need to be used.

So, PR for test for new behavior sounds like a good idea.

**Comment by nbauernfeind** [comment]
While this might seem to be a bug of some sort, this isn't an idiomatic example of scala. Since case classes are intended to be used as immutable tokens, all fields have auto-generated getters -- so it is bit unusual to have an explicit getter too. Stylistically, if I were reviewing your code, I would recommend using a name that is a bit more clear on the additional getter (e.g. why should one prefer to use `Sample#getFoo` over `Sample#foo`?). If you have a more clear name, then this issue disappears.

One quirk that Scala has (w.r.t. Jackson) is that you get so much with so little code. As you point out, the `foo` val in the constructor generates both a field and a getter for free. Courtesy of abstractions, reflecting the run-time java-byte code, and delegating to tools like paranamer, it becomes difficult to differentiate when a getter was explicitly provided versus auto-generated and exactly where an annotation was placed and how/why. Even when you have all of the facts/information it can yet be difficult to guess the developer's intent. This is where, if we were in person, I would shrug and say 'one has to generalize somewhere'.

Sorry for the lack of change documentation - it is super hard to keep track of such compounding interactions with such little time to devote to the project. (And yes, it frustrates us all.)
