### ISSUE TITLE
Objects in tuples are not serialized as ids

### ISSUE THREAD

**Issue by tremaluca** [FasterXML/jackson-module-scala#443]
Using classes annotated with `JsonIdentityInfo` inside of tuples has a weir behaviour
```scala
@JsonIdentityInfo(generator = classOf[ObjectIdGenerators.IntSequenceGenerator])
case class Foo(x: Int)

case class ManyFooPairs(foos: Seq[(Foo, Foo)])

object Main extends App {
  val mapper = new ObjectMapper().registerModule(DefaultScalaModule)
  val f1 = Foo(1)
  val f2 = Foo(2)
  println(mapper.writeValueAsString(
    ManyFooPairs(Seq((f1, f1), (f1, f2)))
  ))
}
```
prints
```json
{"foos":[[{"@id":1,"x":1},{"@id":1,"x":1}],[{"@id":1,"x":1},{"@id":1,"x":2}]]}
```
Introducing a specific pair class solves the issue:
```scala
@JsonIdentityInfo(generator = classOf[ObjectIdGenerators.IntSequenceGenerator])
case class Foo(x: Int)

case class FooPair(l: Foo, r: Foo)

case class ManyFooPairs(foos: Seq[FooPair])

object Main extends App {
  val mapper = new ObjectMapper().registerModule(DefaultScalaModule)
  val f1 = Foo(1)
  val f2 = Foo(2)
  println(mapper.writeValueAsString(
    ManyFooPairs(Seq(FooPair(f1, f1), FooPair(f1, f2)))
  ))
}
```
prints
```json
{"foos":[{"l":{"@id":1,"x":1},"r":1},{"l":1,"r":{"@id":2,"x":2}}]}
```

**Comment by pjfanning** [comment]
This still behaves as described - one potential workaround is to use ObjectIdGenerators.UUIDGenerator - this generates different `@id` values for each serialized instance of foo

**Comment by pjfanning** [comment]
@cowtowncoder the ObjectId code seems to work at the SerializationProvider level - so that if the same SerializationProvider instance sees the same class instance twice, then the second instance gets the same id assigned.

In the example in the issue description, when Foo is wrapped in a class FooPair, the same SerializationProvider instance serializes all the Foo instances. When Foo is wrapped in a Tuple, we seem to end up with different SerializationProvider instances serializing each Foo instance - so the ids all end up as 1. 

Would you have any idea why we end up with multiple SerializationProvider instances in the latter case? All the SerializationProvider instances have the same source SerializationProvider instance - is there any way to delegate the object id map to the source provider?

**Comment by pjfanning** [comment]
This seems to be the fix for the Tuple Serializer:

```
  def serialize(value: Product, jgen: JsonGenerator, provider: SerializerProvider): Unit = {
    jgen.writeStartArray()
    value.productIterator.foreach(provider.writeValue(jgen, _))
    jgen.writeEndArray()
  }
```

**Comment by cowtowncoder** [comment]
Right, without seeing the original code I would speculate that something is calling different underlying `ObjectMapper` instance -- `SerializationProvider` is constructed by mapper when `writeValue()` (and related) is called.
This is why it is generally preferable to call methods either through provided `SerializerProvider` or `JsonGenerator` directly. Jackson 3.0 does actually improve things a lot as well wrt use of `JsonGenerator`.
