### ISSUE TITLE
JsonInclude.Include.NON_NULL is ignored for Option.empty in a map

### ISSUE THREAD

**Issue by meiwin** [FasterXML/jackson-module-scala#46]
// the source code

  val mapper = new ObjectMapper()
  mapper.registerModule(DefaultScalaModule)
  mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL)
  mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)
  mapper.registerModule(DefaultScalaModule)

  val testValue = Map("nothing" -> Option.empty[String])
  mapper.writeValueAsString(testValue) // expect {}, but {"nothing":null} is returned instead

**Comment by sneharathod** [comment]
It isnt working for me :( 
mapper.setDateFormat(new SimpleDateFormat(DATE_FORMAT));   
        mapper.setSerializationInclusion(Include.NON_EMPTY);
      mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

**Comment by cowtowncoder** [comment]
`NON_NULL` check will not work, since "Optionals" (Scala's, JDK8's) are not considered `null`, but rather "absent". 
Furthermore, however, handling as Bean/POJO/POSO property differs from inclusion in Map.
So this:

https://github.com/FasterXML/jackson-databind/issues/818

would need to be implemented to support filtering out of `Option` from Maps, as well as some code changes in Scala map serializers (since they are not `java.util.Map`s).

If functionality is desired, I would suggest filing a new issue, as `NON_NULL` will not work so description here is bit off.
