### ISSUE TITLE
Deserialising serialised maps with case classes as keys or values produces incorrect results

### ISSUE THREAD

**Issue by Martynas-P** [FasterXML/jackson-module-scala#493]
If I have a Map with case class as its key or value, then deserialising from JSON does not work, as the case class becomes a Map or a String. And since the deserialised values refer to types different than the declared variables, accessing them results in a `java.lang.ClassCastException` exception. Below are test cases that can be put in `src/test/scala/com/fasterxml/jackson/module/scala/deser/ListMapTest.scala` to reproduce the issue

```scala
  "Map Serialization" should "handle maps of case classes" in {
    val data: Map[SampleCaseClass, SampleCaseClass] = Map(
      SampleCaseClass(map = Map("a" -> "A")) -> SampleCaseClass(seq = List("a", "A"))
    )

    val deserialized = mapper.readValue(serialize(data), classOf[Map[SampleCaseClass, SampleCaseClass]])

    // Here the key is "SampleCaseClass(Map(a -> A),List())" and value is a Map
    deserialized shouldBe data
  }

  "Map Serialization" should "handle maps with case classes as values" in {
    val data: Map[String, SampleCaseClass] = Map(
      "test" -> SampleCaseClass(seq = List("a", "A"))
    )

    val deserialized = mapper.readValue(serialize(data), classOf[Map[String, SampleCaseClass]])

    // value is a Map
    deserialized shouldBe data
  }

  "Map Serialization" should "handle maps with case classes as keys" in {
    val data: Map[SampleCaseClass, String] = Map(
      SampleCaseClass(seq = List("a", "A")) -> "test"
    )

    val deserialized = mapper.readValue(serialize(data), classOf[Map[SampleCaseClass, String]])

    // key is a String
    deserialized shouldBe data
  }
```

**Comment by pjfanning** [comment]
what would you suggest should be the serialized form of `Map[SampleCaseClass, String]`?

generally when you serialize a Map in json, it is expected the key values can be represented as strings because the json ends up like

```
"map": {
  "key1": "value1",
  "key2": {
    //some object mappings
  }
}
```

TupleKeySerializer in MapSerializerTest is used to serialize a non-standard key - maybe you could start by defining a key serializer.

**Comment by cowtowncoder** [comment]
As @pjfanning pointed out, JSON Object keys are limited to Strings, which is why Jackson has separate handling of value and key (de)serializers.

As a general rule, `Map` keys require custom key (de)serializers, although Jackson provides implementations for some of more commonly used types (many scalar types, Enums, date/time values).

For serialization, I think default otherwise is to just call `toString()`; for deserialization, a single-String-argument constructor will be found and used if defined.

Jackson 2.12 did add one new noteworthy feature: annotation `@JsonKey` which can be added to a method and if so, is used for serialization. Older `@JsonValue` is also used if no `@JsonKey` is specified.

Finally, it is possible to register custom key serializers and deserializers: registered value deserializers and serializers are never used for Map keys.

**Comment by Martynas-P** [comment]
This could be done by representing a Map in JSON as an array where key and vales are entries in it. I understand that you might not want to implement this, but it is possible.

What about the case where Map has String as the key and case class as the value? Are there any problems with deserialising this scenario?

**Comment by cowtowncoder** [comment]
Map should be able to have any otherwise supported value types; only keys are challenging. So case classes as Map values should be fine as far as I know (@pjfanning knows it better than I do tho).

And yes, correct, in theory it would be possible to use different structural mapping to support composite keys -- there are other alternatives too, but it is often simpler to figure out String serialization for key types.

**Comment by pjfanning** [comment]
Closing issue as invalid
