### ISSUE TITLE
Different handling of null and absent value during deserialization

### ISSUE THREAD

**Issue by christianknoepfle** [FasterXML/jackson-module-scala#687]
Hi,

I have asked the following over at stackoverflow ([link to question](https://stackoverflow.com/questions/78807873/different-handling-of-null-and-absent-value-in-json-using-jackson-scala-deserial)) but haven't got any feedback. So I am reprhasing it a bit and hope for some help here. :)

I am deserializing json into Scala case classes using jackson and struggle with handling of optional attributes, default values and null/missing attributes in json.

Let me illustrate with the following example. Given this case class

````scala
case class MyClass(val1: Option[String] = Some("default"))
````

What I am expecting:
- If the attribute `val1` is **missing** in the json, the case class is initialized with the default (just as it would happen in pure scala code, e.g. `MyClass()`, then `val1` is `Some("default")` ). 
- If the json **contains** `val1` then the value is taken for initialization. And it should not matter whether that value is a string (e.g. "hi") or  `null `. So same as in pure scala it would be  `MyClass(Some("hi")) ` or  `MyClass(None) `.

The issue is that having a json with `{"val1": null}` the case class is not initialized with `None` but with the provided default value. 

I am using jackson 2.15.3. 

A scalatest including all needed code to demonstrate the issue  can be found [here](https://stackoverflow.com/questions/78807873/different-handling-of-null-and-absent-value-in-json-using-jackson-scala-deserial)

Any ideas someone? Is that even possible with jackson? 

Thanks a lot, best regards

Christian

**Comment by pjfanning** [comment]
https://stackoverflow.com/questions/74170291/how-to-handle-deserialization-of-null-and-absent-properties-with-jackson may actually be the best way to go if you can modify your class a bit.

**Comment by pjfanning** [comment]
also https://stackoverflow.com/questions/18805455/setting-default-values-to-null-fields-when-mapping-with-jackson might be worth reading

**Comment by pjfanning** [comment]
All in all, I think it will be a struggle to get the behaviour you want from Jackson in this case. Jackson is a Java tool. This module is a hack to allow some Scala support.
To tell you the truth, I rarely use Jackson when I use Scala - I tend to use JSON tools that are designed specifically for Scala. Jsoniter-Scala, Circe, Play-JSON, etc.

This module is useful for cases where you need Java and Scala support - places like Apache Spark, Akka, Apache Pekko, etc.

The real issue here is I am not sure how best to get jackson-databind to share the info with this module that input is explicitly null or if it is missing. So far, it has not proved to be something that worries most users.

**Comment by christianknoepfle** [comment]
Hi, thank you very much for your speedy and extensive answer and sorry for my late response. I feared that it will get either complicated or "different tooling". After looking through the various links I think I will try out some of the alternatives.

Again, thanks for your response and help, best Christian
