### ISSUE TITLE
Traversable class serializes funny (empty/traversableAgain)

### ISSUE THREAD

**Issue by dhelder** [FasterXML/jackson-module-scala#94]
I'm using Jackson 2.2.2.

``` scala
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
val mapper = new ObjectMapper()
class C extends Traversable[C] { def foreach[Unit](f : (C => Unit)) { } }
```

```
scala> mapper.writeValueAsString(new C)
res7: java.lang.String = {"empty":true,"traversableAgain":true}
```

I'd expect the output to be "{}".

This thread suggests it's using beans serialization.
http://stackoverflow.com/questions/12113010/scala-responsebody-and-map

**Comment by ExpandingShapes** [comment]
For those who find this page in their times of struggle (just as I did yesterday) all you gotta do to sole the problem is to add JacksonConfig with DefaultScalaModule included. Or include the module if you already have the config

`
JsonMapper.builder()
  .addModule(DefaultScalaModule)
  .build()
`
from jackson-module-scala README
OR
`
ObjectMapper()
      .registerModule(DefaultScalaModule)
`
